error-reading-csv

Processing 2023-03-08-18-28-02.bag
[ INFO] [1678892667.927262858]: Opening /home/petrmiculek/catkin_ws/Data/recordings-2/2023-03-08-18-28-02.bag
Waiting 0.2 seconds after advertising topics... done.

Hit space to toggle paused, or 's' to step.

Done.
2023-03-08-18-28-02.bag: 131 lines
Traceback (most recent call last):
  File "/home/petrmiculek/catkin_ws/src/follow_me/src/evaluation.py", line 26, in <module>
    df = pd.read_csv(sys.argv[1], header=None, names=['t', 'number_of_persons'], encoding='utf-8')
  File "/home/petrmiculek/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
    return func(*args, **kwargs)
  File "/home/petrmiculek/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
    return func(*args, **kwargs)
  File "/home/petrmiculek/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/petrmiculek/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    return parser.read(nrows)
  File "/home/petrmiculek/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File "/home/petrmiculek/.local/lib/python3.10/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File "pandas/_libs/parsers.pyx", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File "pandas/_libs/parsers.pyx", line 866, in pandas._libs.parsers.TextReader._read_rows
  File "pandas/_libs/parsers.pyx", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File "pandas/_libs/parsers.pyx", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Buffer overflow caught - possible malformed input file.
